language: python
python:
  - "3.6"
# setup
setup:
  - pip install pipenv
# command to install dependencies
install:
  - pipenv install --dev
# command to run tests
script:
  - pipenv run pytest --verbose
