name: wemake style

on:
  pull_request:
    branches:
      - lala-master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: wemake-services/wemake-python-styleguide@master